from .document_text_template_edit import DocumentTextTemplateEdit
from .object_processing import DocumentObjectProcessingView
from .object_deletion import document_object_deletion_view
from .objects_tree import ObjectsTree
from .save_text_template import save_text_template_view
from .object_tree_correctness_check import object_tree_correctnes_check_view