# Generated by Django 3.2.4 on 2022-02-19 10:51

from django.db import migrations


def replace_doubled_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')
    users = User.objects.all()
    emails = []

    for user in users:
        if not user.email or user.email in emails:
            user.email = f'test{user.pk}@test.test'
            user.save()
        else:
            emails.append(user.email)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20220219_1849'),
    ]

    operations = [
        migrations.RunPython(replace_doubled_emails),
    ]
