# Generated by Django 3.2.4 on 2022-02-19 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_profiles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Profile = apps.get_model('users', 'Profile')
    users = User.objects.all()

    for user in users:
        profile = Profile.objects.filter(user=user)
        if not profile.exists():
            Profile.objects.create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_replace_doubled_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender',
                 models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Не указан')], default='U',
                                  max_length=1, verbose_name='Пол')),
                ('birthday_at', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Очество')),
                ('activation_key', models.CharField(blank=True, max_length=128)),
                ('activation_key_expires', models.DateTimeField(blank=True, null=True)),
                ('password_recovery_key', models.CharField(blank=True, max_length=128)),
                ('password_recovery_key_expires', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles),
    ]
