# Generated by Django 3.2.4 on 2022-06-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
