# Generated by Django 3.2.4 on 2022-06-21 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220603_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ключ активации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ключ активации годен до'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password_recovery_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ключ восстановления пароля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password_recovery_key_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ключ восстановления пароля годен до'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
