# Generated by Django 3.2.4 on 2022-09-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220621_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_klz',
            field=models.BooleanField(default=False, verbose_name='Член КЛЗ'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False, verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_redactor',
            field=models.BooleanField(default=False, verbose_name='Редактор'),
        ),
    ]
