# Generated by Django 3.2.4 on 2022-11-26 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220621_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_friends',
            field=models.ManyToManyField(null=True, related_name='users_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
