# Generated by Django 3.2.4 on 2022-11-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_options'),
        ('users', '0010_auto_20220902_2028'),
    ]

    operations = [
    ]
