# Generated by Django 3.2.4 on 2022-11-28 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_friends',
            field=models.ManyToManyField(blank=True, related_name='users_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
