# Generated by Django 3.2.4 on 2022-11-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_user_friends'),
        ('users', '0011_merge_20221121_2016'),
    ]

    operations = [
    ]
