# Generated by Django 3.2.4 on 2022-11-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220902_2028'),
        ('users', '0011_alter_user_user_friends'),
    ]

    operations = [
    ]
