# Generated by Django 3.2.4 on 2023-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20221206_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный человек'),
        ),
    ]
