# Generated by Django 3.2.4 on 2023-01-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Секция меню в шапке пользователя',
                'verbose_name_plural': 'Секции меню в шапке пользователя',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(blank=True, to='users.MenuSections', verbose_name='Секции, разрешенные к показу'),
        ),
    ]
