# Generated by Django 3.2.4 on 2023-01-30 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_friends',
            field=models.ManyToManyField(blank=True, editable=False, related_name='users_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
