# Generated by Django 3.2.4 on 2023-02-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0052_znanie_notification'),
        ('users', '0017_alter_user_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='knowledge_to_notification_page',
            field=models.ManyToManyField(blank=True, related_name='notificated_users', to='drevo.Znanie', verbose_name='Знания для страницы уведомлений'),
        ),
    ]
