# Generated by Django 3.2.4 on 2023-06-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_knowledge_to_notification_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie_acceptance',
            field=models.BooleanField(default=False, verbose_name='Согласие использования файлов cookie'),
        ),
    ]
