# Generated by Django 3.2.4 on 2023-08-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0072_merge_0071_alter_appeal_subject_0071_relation_order'),
        ('users', '0020_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSuggection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заглавние знание')),
                ('is_approve', models.BooleanField(blank=True, default=None, null=True, verbose_name='Результат проверки предложения')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expert', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт, вынесший вердикт')),
                ('knowledge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.tz', verbose_name='Вид знания')),
                ('parent_knowlege', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drevo.znanie', verbose_name='Родительское знание')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.tr', verbose_name='Вид связи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, предложивший знание')),
            ],
        ),
    ]
