# Generated by Django 3.2.4 on 2023-09-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0072_merge_0071_alter_appeal_subject_0071_relation_order'),
        ('users', '0022_auto_20230828_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersuggection',
            options={'verbose_name': 'Пользовательское предложение', 'verbose_name_plural': 'Пользовательские предложения'},
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='parent_knowlege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drevo.znanie', verbose_name='Родительское знание'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.tr', verbose_name='Вид связи'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='users.user', verbose_name='Пользователь, предложивший знание'),
        ),
    ]
