# Generated by Django 3.2.4 on 2023-09-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20230828_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersuggection',
            options={'verbose_name': 'Пользовательское предложение', 'verbose_name_plural': 'Пользовательские предложения'},
        ),
    ]
