# Generated by Django 3.2.4 on 2023-09-11 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0072_merge_0071_alter_appeal_subject_0071_relation_order'),
        ('users', '0023_auto_20230903_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggection',
            name='parent_knowlege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drevo.znanie', verbose_name='Родительское знание'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, предложивший знание'),
        ),
    ]
