# Generated by Django 3.2.4 on 2023-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20230911_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionType',
            fields=[
                ('type_name', models.CharField(max_length=256, verbose_name='Название типа')),
                ('is_private', models.BooleanField(blank=True, default=False, verbose_name='Является ли тип частным')),
                ('weight', models.IntegerField(primary_key=True, serialize=False, verbose_name='Вес для сортировки')),
            ],
            options={
                'verbose_name': 'Вид предложения',
                'verbose_name_plural': 'Виды предложений',
            },
        ),
    ]
