# Generated by Django 3.2.4 on 2023-09-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20230919_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestiontype',
            name='is_private',
        ),
    ]
