# Generated by Django 3.2.4 on 2023-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_suggestiontype_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestiontype',
            name='type_name',
            field=models.CharField(max_length=255, verbose_name='Название типа'),
        ),
    ]
