# Generated by Django 3.2.4 on 2023-10-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_usersuggection_options'),
        ('users', '0028_alter_suggestiontype_type_name'),
    ]

    operations = [
    ]
