# Generated by Django 3.2.4 on 2023-10-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_20231003_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Заглавие предложения'),
        ),
    ]
