# Generated by Django 3.2.4 on 2023-10-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_5_intermediate_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersuggection',
            name='knowledge_type',
        ),
        migrations.RemoveField(
            model_name='usersuggection',
            name='knowledge_type_id',
        ),
        migrations.RemoveField(
            model_name='usersuggection',
            name='relation_type',
        ),
    ]
