# Generated by Django 3.2.4 on 2023-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20231006_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestiontype',
            name='type_name',
            field=models.CharField(max_length=254, verbose_name='Название типа'),
        ),
    ]
