# Generated by Django 3.2.4 on 2023-10-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20231006_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersuggection',
            name='knowledge_type',
        ),
        migrations.RemoveField(
            model_name='usersuggection',
            name='relation_type',
        ),
    ]
