# Generated by Django 3.2.4 on 2023-10-13 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0078_merge_20231003_2326'),
        ('users', '0032_alter_suggestiontype_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersuggection',
            options={'verbose_name': 'Предложение пользователя', 'verbose_name_plural': 'Предложения пользователей'},
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='is_approve',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Результат проверки'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Предложение'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='parent_knowlege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drevo.znanie', verbose_name='Знание'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
