# Generated by Django 3.2.4 on 2023-10-18 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0080_suggestion_suggestiontype'),
        ('users', '0033_auto_20231014_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggection',
            name='expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_suggestions2', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='parent_knowlege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='znaine2', to='drevo.znanie', verbose_name='Знание'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='suggestions_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_type2', to='users.suggestiontype', verbose_name='Вид предложения'),
        ),
        migrations.AlterField(
            model_name='usersuggection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
