# Generated by Django 3.2.4 on 2023-10-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20231018_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersuggection',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='usersuggection',
            name='parent_knowlege',
        ),
        migrations.RemoveField(
            model_name='usersuggection',
            name='suggestions_type',
        ),
        migrations.RemoveField(
            model_name='usersuggection',
            name='user',
        ),
        migrations.DeleteModel(
            name='SuggestionType',
        ),
        migrations.DeleteModel(
            name='UserSuggection',
        ),
    ]
