# Generated by Django 3.2.4 on 2024-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20240229_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
    ]
