# Generated by Django 3.2.4 on 2024-04-01 13:31

from django.db import migrations, models


def migrate_patronymic(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        if hasattr(user, 'profile') and user.profile.patronymic:
            user.patronymic = user.profile.patronymic
            user.save()


def move_patronymic_back_to_profile(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        if hasattr(user, 'profile') and user.patronymic:
            user.profile.patronymic = user.patronymic
            user.profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0037_auto_20240229_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.RunPython(migrate_patronymic, move_patronymic_back_to_profile),
        migrations.RemoveField(
            model_name='profile',
            name='patronymic',
        ),
    ]
