# Generated by Django 3.2.4 on 2022-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='url_tag',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='URL тег адреса'),
        ),
    ]