# Generated by Django 4.1.1 on 2023-02-02 17:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_group', models.BooleanField(default=False, verbose_name='Группа')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='help.help', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Раздел помощь',
                'verbose_name_plural': 'Разделы помощи',
            },
        ),
        migrations.CreateModel(
            name='HelpURLTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'URL тег страницы "Помощь"',
                'verbose_name_plural': 'URL теги страницы "Помощь"',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='helppage',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryHelp',
        ),
        migrations.DeleteModel(
            name='HelpPage',
        ),
        migrations.AddField(
            model_name='help',
            name='url_tag',
            field=models.ManyToManyField(blank=True, related_name='help', to='help.helpurltag', verbose_name='Тег URL'),
        ),
    ]
