# Generated by Django 3.2.4 on 2022-10-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
    ]
