# Generated by Django 3.2.4 on 2024-08-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_help_helpurltag_remove_helppage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='help.help', verbose_name='Ярлык'),
        ),
    ]
