# Generated by Django 3.2.4 on 2022-10-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_tagshelppage_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagshelppage',
            name='tag',
            field=models.CharField(default='s', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
