# Generated by Django 3.2.4 on 2022-10-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_helppage_url_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppage',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
