# Generated by Django 3.2.4 on 2022-10-26 14:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_helppage_url_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppage',
            name='url_tag',
        ),
        migrations.CreateModel(
            name='CategoryHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание категории')),
                ('url_tag', models.CharField(blank=True, max_length=20, unique=True, verbose_name='URL тег адреса')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='help.categoryhelp')),
            ],
            options={
                'verbose_name': 'Категория помощи',
                'verbose_name_plural': 'Категории помощи',
            },
        ),
        migrations.AddField(
            model_name='helppage',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='help', to='help.categoryhelp', unique=True, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
