# Generated by Django 4.1.1 on 2023-01-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_help_helpurltag_remove_helppage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='help',
            name='url_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_category', to='help.helpurltag', verbose_name='URL тег адреса'),
        ),
        migrations.AlterField(
            model_name='helpurltag',
            name='tag',
            field=models.CharField(help_text='Введите необходимые теги по порядку через запятую или пробел. Пример: znanie, grade, group, infographics -> /znanie/grade/group/infographics', max_length=255, unique=True, verbose_name='URL тег адреса'),
        ),
    ]
