# Generated by Django 3.2.4 on 2022-10-06 08:28

from django.db import migrations, models
import django.db.models.deletion
import help.validators


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_alter_tagshelppage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helppage',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='help.tagshelppage'),
        ),
        migrations.AlterField(
            model_name='tagshelppage',
            name='tag',
            field=models.CharField(max_length=20, unique=True, validators=[help.validators.validate_tag]),
        ),
    ]
