# Generated by Django 4.1.1 on 2023-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_alter_help_content_alter_help_url_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpurltag',
            options={'ordering': ['name'], 'verbose_name': 'URL тег страницы "Помощь"', 'verbose_name_plural': 'URL теги страницы "Помощь"'},
        ),
        migrations.RemoveField(
            model_name='helpurltag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='help',
            name='url_tag',
        ),
        migrations.AddField(
            model_name='help',
            name='url_tag',
            field=models.ManyToManyField(blank=True, related_name='help', to='help.helpurltag', verbose_name='Тег URL'),
        ),
    ]
