# Generated by Django 3.2.4 on 2022-10-10 12:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0023_auto_20221004_1056'),
        ('help', '0003_helppage_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppage',
            name='categoty',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='help', to='drevo.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helppage',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать?'),
        ),
    ]
