# Generated by Django 3.2.4 on 2022-10-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20221010_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helppage',
            old_name='categoty',
            new_name='category',
        ),
    ]
