# Generated by Django 3.2.4 on 2022-10-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20221006_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helppage',
            name='id',
        ),
        migrations.AlterField(
            model_name='helppage',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='help.tagshelppage'),
        ),
    ]
