# Generated by Django 4.1.1 on 2023-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_alter_helpurltag_options_remove_helpurltag_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpurltag',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название тега'),
        ),
    ]
