# Generated by Django 3.2.4 on 2022-10-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_alter_helppage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='help', to='help.categoryhelp', verbose_name='Категория'),
        ),
    ]
