# Generated by Django 3.2.4 on 2022-10-16 20:29

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0008_alter_helppage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='help', to='help.categoryhelp', unique=True, verbose_name='Категория'),
        ),
    ]
