# Generated by Django 3.2.4 on 2022-10-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmbr_answers', models.SmallIntegerField(verbose_name='Число ответов')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_question', to='interview.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='interview.question')),
            ],
        ),
    ]
