# Generated by Django 3.2.4 on 2022-10-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='questions',
        ),
    ]
