# Generated by Django 3.2.4 on 2022-10-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_interview_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='nmbr_answers',
            field=models.SmallIntegerField(default=1, verbose_name='Макс число ответов'),
        ),
    ]
