# Generated by Django 3.2.4 on 2022-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20221005_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
