# Generated by Django 3.2.4 on 2022-10-06 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0005_auto_20221005_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Интервью', 'verbose_name_plural': 'Интервью'},
        ),
        migrations.AlterField(
            model_name='interview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL, verbose_name='Автор интервью'),
        ),
    ]
