# Generated by Django 3.2.4 on 2022-10-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20221006_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='is_closed',
        ),
    ]
