# Generated by Django 3.2.4 on 2022-10-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0021_auto_20221004_1623'),
        ('interview', '0007_remove_interview_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='c_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drevo.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='interview.question', verbose_name='Вопрос'),
        ),
    ]
