# Generated by Django 3.2 on 2021-04-28 18:56

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='Tz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drevo.tz')),
            ],
            options={
                'verbose_name': 'Вид знания',
                'verbose_name_plural': 'Виды знания',
            },
        ),
        migrations.CreateModel(
            name='Znanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Тема')),
                ('content', models.TextField(blank=True, max_length=512, null=True, verbose_name='Содержание')),
                ('href', models.URLField(help_text='укажите www-адрес источника', verbose_name='Источник')),
                ('source_com', models.CharField(max_length=128, verbose_name='Комментарий к источнику')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(help_text='укажите автора', on_delete=django.db.models.deletion.PROTECT, to='drevo.author', verbose_name='Автор')),
                ('rz', models.ForeignKey(help_text='укажите связанное знание', on_delete=django.db.models.deletion.PROTECT, to='drevo.znanie', verbose_name='Связанное знание')),
                ('tz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.tz', verbose_name='Вид знания')),
            ],
            options={
                'verbose_name': 'Знание',
                'verbose_name_plural': 'Знания',
                'ordering': ('name',),
            },
        ),
    ]
