# Generated by Django 3.2.4 on 2022-05-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationGradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Наименование оценки')),
                ('value', models.FloatField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Градация',
                'verbose_name_plural': 'Шкала оценок связей',
                'ordering': ('-value',),
            },
        ),
        migrations.CreateModel(
            name='RelationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.relationgradescale', verbose_name='Оценка связи')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='drevo.relation', verbose_name='Связь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка связи',
                'verbose_name_plural': 'Оценки связей',
                'unique_together': {('user', 'relation')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.knowledgegradescale', verbose_name='Оценка знания')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='drevo.znanie', verbose_name='Знание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка знания',
                'verbose_name_plural': 'Оценки знаний',
                'unique_together': {('user', 'knowledge')},
            },
        ),
    ]
