# Generated by Django 3.2.4 on 2021-11-25 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0001_squashed_0052_auto_20211124_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tz',
            options={'ordering': ('order',), 'verbose_name': 'Вид знания', 'verbose_name_plural': 'Виды знания'},
        ),
        migrations.AlterField(
            model_name='relation',
            name='author',
            field=models.ForeignKey(help_text='укажите автора', on_delete=django.db.models.deletion.PROTECT, to='drevo.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='tr',
            field=models.ForeignKey(help_text='укажите вид связи', on_delete=django.db.models.deletion.PROTECT, to='drevo.tr', verbose_name='Вид связи'),
        ),
        migrations.AlterField(
            model_name='tz',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='укажите порядковый номер', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='znanie',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
