# Generated by Django 3.2 on 2021-04-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znanie',
            name='rz',
            field=models.ForeignKey(blank=True, help_text='укажите связанное знание', null=True, on_delete=django.db.models.deletion.PROTECT, to='drevo.znanie', verbose_name='Связанное знание'),
        ),
    ]
