# Generated by Django 3.2.4 on 2022-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0002_auto_20211125_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posishenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='znanie',
            name='visits',
            field=models.IntegerField(blank=0, null=True),
        ),
    ]
