# Generated by Django 3.2.4 on 2022-02-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0003_auto_20220217_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posishenia',
        ),
    ]
