# Generated by Django 3.2.4 on 2022-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0004_delete_posishenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znanie',
            name='visits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
