# Generated by Django 3.2.4 on 2022-04-01 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0004_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='znrating',
            options={'verbose_name': 'Рейтинг знаний', 'verbose_name_plural': 'Рейтинг знаний'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='Тело комментария')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='drevo.comment', verbose_name='Родительский комментарий')),
                ('znanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drevo.znanie', verbose_name='Знание')),
            ],
            options={
                'verbose_name': 'Комментарий знания',
                'verbose_name_plural': 'Комментарии знаний',
                'ordering': ('-created_at',),
            },
        ),
    ]
