# Generated by Django 3.2.4 on 2022-04-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0005_auto_20220401_2156'),
        ('drevo', '0005_visits'),
    ]

    operations = [
    ]
