# Generated by Django 3.2.4 on 2022-04-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0007_tz_is_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tz',
            name='is_group',
        ),
    ]
