# Generated by Django 3.2.4 on 2022-04-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0009_tz_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr',
            name='argument_type',
            field=models.BooleanField(choices=[(False, 'За'), (True, 'Против')], default=False, verbose_name='Тип довода'),
        ),
        migrations.AddField(
            model_name='tr',
            name='is_argument',
            field=models.BooleanField(default=False, verbose_name='Доказательная связь'),
        ),
        migrations.AddField(
            model_name='tz',
            name='can_be_rated',
            field=models.BooleanField(default=False, verbose_name='Возможна оценка знания'),
        ),
    ]
