# Generated by Django 3.2.4 on 2022-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0010_auto_20220421_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Наименование оценки')),
                ('low_value', models.FloatField(verbose_name='Нижнее значение')),
                ('high_value', models.FloatField(verbose_name='Верхнее значение')),
                ('is_high_in_range', models.BooleanField(default=False, verbose_name='Диапазон включает верхнее значение')),
            ],
            options={
                'verbose_name': 'Градация',
                'verbose_name_plural': 'Шкала оценок знаний',
                'ordering': ('-high_value',),
            },
        ),
    ]
