# Generated by Django 3.2.4 on 2022-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0011_knowledgegradescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationGradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Наименование оценки')),
                ('value', models.FloatField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Градация',
                'verbose_name_plural': 'Шкала оценок связей',
                'ordering': ('-value',),
            },
        ),
    ]
