# Generated by Django 3.2.4 on 2022-04-21 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0012_relationgradescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.knowledgegradescale', verbose_name='Оценка')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='drevo.znanie', verbose_name='Знание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки знаний',
                'unique_together': {('user', 'knowledge')},
            },
        ),
    ]
