# Generated by Django 3.2.4 on 2022-05-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0012_auto_20220426_1733'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
