# Generated by Django 3.2.4 on 2022-05-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0013_auto_20220528_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsinghistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра'),
        ),
    ]
