# Generated by Django 3.2.4 on 2022-04-21 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0013_knowledgegrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgegrade',
            options={'verbose_name': 'Оценка знания', 'verbose_name_plural': 'Оценки знаний'},
        ),
        migrations.AlterField(
            model_name='knowledgegrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.knowledgegradescale', verbose_name='Оценка знания'),
        ),
        migrations.CreateModel(
            name='RelationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.relationgradescale', verbose_name='Оценка связи')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='drevo.relation', verbose_name='Связь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка связи',
                'verbose_name_plural': 'Оценки связей',
                'unique_together': {('user', 'relation')},
            },
        ),
    ]
