# Generated by Django 3.2.4 on 2022-05-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0013_alter_category_managers'),
        ('drevo', '0014_alter_browsinghistory_date'),
    ]

    operations = [
    ]
