# Generated by Django 3.2.4 on 2022-08-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drevo", "0018_interviewanswerexpertproposal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewanswerexpertproposal",
            name="is_yesno_answer_argument",
        ),
    ]
