# Generated by Django 3.2.4 on 2022-08-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0018_interviewanswerexpertproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='znanie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='znanie',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_expert', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='znanie',
            name='redactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redactor', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='znanie',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='user2user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
