# Generated by Django 3.2.4 on 2022-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drevo", "0019_remove_interviewanswerexpertproposal_is_yesno_answer_argument"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="interviewanswerexpertproposal",
            constraint=models.UniqueConstraint(
                fields=("answer", "expert", "interview"),
                name="single_proposal_from_expert_on_answer",
            ),
        ),
    ]
