# Generated by Django 3.2.4 on 2022-09-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0019_auto_20220902_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znanie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='znanie',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_expert', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='znanie',
            name='redactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redactor', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
    ]
