# Generated by Django 4.1.1 on 2022-09-28 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0020_friendsinviteterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='znanie',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='Пересылать'),
        ),
        migrations.AlterField(
            model_name='friendsterm',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Друг'),
        ),
        migrations.AlterField(
            model_name='friendsterm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
