# Generated by Django 4.1.1 on 2022-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0021_znanie_is_send_alter_friendsterm_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tz',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='Пересылать'),
        ),
    ]
