# Generated by Django 3.2.4 on 2022-10-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0022_auto_20221030_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageusersscale',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Правая граница возраста'),
        ),
        migrations.AlterField(
            model_name='ageusersscale',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Левая граница возраста'),
        ),
    ]
