# Generated by Django 3.2.4 on 2022-10-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drevo", "0022_auto_20221004_1055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewanswerexpertproposal",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interview_proposals",
                to="drevo.znanie",
                verbose_name="Интервью",
            ),
        ),
        migrations.AlterField(
            model_name="interviewanswerexpertproposal",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="question_proposals",
                to="drevo.znanie",
            ),
        ),
    ]
