# Generated by Django 3.2.4 on 2022-10-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drevo", "0023_auto_20221004_1056"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="interviewanswerexpertproposal",
            name="can't place new text with link to exist answer",
        ),
    ]
