# Generated by Django 3.2.4 on 2022-10-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0023_auto_20221004_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendsinviteterm',
            options={'verbose_name': 'Заявка в друзья', 'verbose_name_plural': 'Заявки в друзья'},
        ),
        migrations.AlterModelOptions(
            name='friendsterm',
            options={'verbose_name': 'Дружба', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.RemoveField(
            model_name='friendsinviteterm',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='friendsinviteterm',
            name='date_added',
        ),
    ]
