# Generated by Django 3.2.4 on 2022-10-27 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0024_remove_constrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='znanie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='znanie',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_expert', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='znanie',
            name='redactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redactor', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.CreateModel(
            name='KnowledgeStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PUB_PRE', 'Опубликованное ПредЗнание'), ('PUB', 'Опубликованное Знание'), ('WORK_PRE', 'ПредЗнание в работе'), ('RET_PRE_EDIT', 'Возврат ПредЗнания на доработку'), ('PRE_FIN', 'Готовое ПредЗнание'), ('PRE_EXP', 'Экспертиза ПредЗнания'), ('PRE_REJ', 'Отклоненное ПредЗнание'), ('PRE_REF_EXP', 'Возврат ПредЗнания на экспертизу'), ('PRE_FIN_EXP', 'Завершенное ПредЗнание'), ('WORK', 'Знание в работе'), ('RET_TO_EDIT', 'Возврат Знания на доработку'), ('FIN', 'Завершенное Знание'), ('PRE_REDACT', 'ПредЗнание на редактировании'), ('PRE_REF_RED', 'Возврат ПредЗнания редактору'), ('PRE_FIN_RED', 'ПредЗнание к публикации'), ('REDACT', 'Знание на редактировании'), ('REF_RED', 'Возврат Знания редактору'), ('FIN_RED', 'Знание к публикации'), ('PRE_KLZ', 'ПредЗнание в КЛЗ'), ('PRE_EXP_2', 'Экспертиза-2 ПредЗнания'), ('KLZ', 'Знание в КЛЗ'), ('EXP_2', 'Экспертиза-2 Знания'), ('REJ', 'Отклоненное Знание')], default=None, max_length=12, null=True, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_limit', models.IntegerField(default=1000, verbose_name='Лимит времени')),
                ('is_active', models.BooleanField(default=True, verbose_name='Текущий статус')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_status', to='drevo.znanie', verbose_name='Знание')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_know_status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус знания',
                'verbose_name_plural': 'Статусы знания',
            },
        ),
    ]
