# Generated by Django 3.2.4 on 2022-10-28 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drevo", "0024_auto_20221024_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="subscribers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
