# Generated by Django 3.2.4 on 2022-10-29 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0025_auto_20221028_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelFeedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='FeedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=511, verbose_name='Текст сообщения')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('was_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drevo.labelfeedmessage', verbose_name='Ярлык сообщения')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('znanie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_znanie', to='drevo.znanie', verbose_name='Знание')),
            ],
        ),
    ]
