# Generated by Django 4.1.1 on 2022-10-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0025_auto_20221028_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswerexpertproposal',
            name='duplicate_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_answer_proposals', to='drevo.znanie', verbose_name='Ответ для дублей'),
        ),
    ]
