# Generated by Django 3.2.4 on 2022-11-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drevo", "0026_feedmessage_labelfeedmessage"),
        ("drevo", "0026_interviewanswerexpertproposal_duplicate_answer"),
    ]

    operations = []
