# Generated by Django 4.1.1 on 2022-11-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0026_feedmessage_labelfeedmessage'),
        ('drevo', '0026_interviewanswerexpertproposal_duplicate_answer'),
    ]

    operations = [
    ]
