# Generated by Django 3.2.4 on 2022-11-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drevo", "0027_merge_20221108_1648"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedmessage",
            options={
                "verbose_name": "Сообщение ленты",
                "verbose_name_plural": "Сообщения ленты",
            },
        ),
        migrations.AlterModelOptions(
            name="labelfeedmessage",
            options={
                "verbose_name": "Ярлык сообщений ленты",
                "verbose_name_plural": "Ярлыки сообщений ленты",
            },
        ),
    ]
