# Generated by Django 3.2.4 on 2022-11-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0023_auto_20221030_2244'),
        ('drevo', '0028_auto_20221109_0820'),
    ]

    operations = [
    ]
