# Generated by Django 3.2.4 on 2022-11-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drevo", "0028_alter_feedmessage_options_and_more"),
        ("drevo", "0028_auto_20221109_0820"),
    ]

    operations = []
