# Generated by Django 3.2.4 on 2022-11-28 13:30

from django.db import migrations

def from_friendsterm_to_user_friends(apps, schema_editor):
    FriendsTerm = apps.get_model('drevo', 'FriendsTerm')
    User = apps.get_model('users', 'User')

    friendships_from_previous_table = FriendsTerm.objects.all()
    friendships_unique = []

    for i in range(0, len(friendships_from_previous_table), 2):
        friendships_unique.append(friendships_from_previous_table[i])
    
    for i in range(len(friendships_unique)):
        user_to_add = User.objects.get(id = friendships_unique[i].user.id)
        friend_to_add = User.objects.get(id = friendships_unique[i].friend.id)

        if not (user_to_add.user_friends.filter(id = friend_to_add.id).exists() or friend_to_add.user_friends.filter(id = user_to_add.id).exists()): 
            user_to_add.user_friends.add(friend_to_add)
    
    for x in friendships_from_previous_table.iterator():
        x.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0028_auto_20221109_0820'),
    ]

    operations = [
        migrations.RunPython(from_friendsterm_to_user_friends)
    ]
