# Generated by Django 3.2.4 on 2022-11-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0029_migration_previous_friends_to_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsTerm',
        ),
    ]
