# Generated by Django 3.2.4 on 2022-11-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0030_auto_20221118_2101'),
        ('drevo', '0030_delete_friendsterm'),
    ]

    operations = [
    ]
