# Generated by Django 3.2.4 on 2022-11-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0029_merge_0023_auto_20221030_2244_0028_auto_20221109_0820'),
        ('drevo', '0030_auto_20221118_2101'),
    ]

    operations = [
    ]
