# Generated by Django 4.1.1 on 2022-12-23 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0030_interviewresultssendingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresultssendingschedule',
            name='interview',
            field=models.ForeignKey(help_text='Выберите знание, вид которого "Интервью"', on_delete=django.db.models.deletion.CASCADE, related_name='sending_schedule', to='drevo.znanie', unique=True, verbose_name='Интервью'),
        ),
    ]
