# Generated by Django 3.2.4 on 2022-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0031_merge_0030_auto_20221118_2101_0030_delete_friendsterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Термин'),
        ),
        migrations.AlterField(
            model_name='tr',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='znanie',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тема'),
        ),
    ]
