# Generated by Django 3.2.4 on 2022-11-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0030_delete_friendsterm'),
        ('drevo', '0031_merge_20221121_2017'),
    ]

    operations = [
    ]
