# Generated by Django 3.2.4 on 2022-12-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0032_merge_20221130_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='znanie',
            name='has_link',
            field=models.BooleanField(default=True, verbose_name='Есть ссылка'),
        )
    ]
