# Generated by Django 3.2.4 on 2022-12-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0034_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='znanie',
            name='show_link',
            field=models.BooleanField(default=True, verbose_name='Отображать как ссылку?'),
        ),
    ]
