# Generated by Django 4.1.1 on 2022-12-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0031_alter_interviewresultssendingschedule_interview'),
        ('drevo', '0035_auto_20221223_1251'),
    ]

    operations = [
    ]
