# Generated by Django 4.1.1 on 2022-12-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0036_merge_20221223_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresultssendingschedule',
            name='interview',
            field=models.OneToOneField(help_text='Выберите знание, вид которого "Интервью"', on_delete=django.db.models.deletion.CASCADE, related_name='sending_schedule', to='drevo.znanie', verbose_name='Интервью'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_quizzes', to='drevo.znanie', verbose_name='Тест'),
        ),
    ]
