# Generated by Django 3.2.4 on 2022-12-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0036_alter_quizresult_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsTerm',
        ),
    ]
