# Generated by Django 4.1.1 on 2022-12-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0037_alter_interviewresultssendingschedule_interview_and_more'),
        ('drevo', '0037_delete_friendsterm'),
    ]

    operations = [
    ]
