# Generated by Django 4.1.1 on 2023-01-06 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0038_merge_20221226_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория параметра',
                'verbose_name_plural': 'Категории параметров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SettingsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название параметра')),
                ('default_param', models.CharField(max_length=255, verbose_name='Значение по умолчанию')),
                ('admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='drevo.parametercategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Параметр настроек',
                'verbose_name_plural': 'Параметры настроек',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_value', models.CharField(blank=True, max_length=255, verbose_name='Значение параметра')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_params', to='drevo.settingsoptions', verbose_name='Параметр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_params', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Параметр пользователя',
                'verbose_name_plural': 'Параметры пользователя',
                'ordering': ['param'],
            },
        ),
    ]
