# Generated by Django 3.2.4 on 2023-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0038_merge_20221226_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationgradescale',
            options={'ordering': ('-high_value',), 'verbose_name': 'Градация', 'verbose_name_plural': 'Шкала оценок связей'},
        ),
        migrations.RemoveField(
            model_name='relationgradescale',
            name='value',
        ),
        migrations.AddField(
            model_name='relationgradescale',
            name='high_value',
            field=models.FloatField(default=0.0, verbose_name='Верхнее значение'),
        ),
        migrations.AddField(
            model_name='relationgradescale',
            name='is_high_in_range',
            field=models.BooleanField(default=False, verbose_name='Диапазон включает верхнее значение'),
        ),
        migrations.AddField(
            model_name='relationgradescale',
            name='is_low_in_range',
            field=models.BooleanField(default=False, verbose_name='Диапазон включает нижнее значение'),
        ),
        migrations.AddField(
            model_name='relationgradescale',
            name='low_value',
            field=models.FloatField(default=0.0, verbose_name='Нижнее значение'),
        ),
    ]
