# Generated by Django 4.1.1 on 2023-01-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0039_parametercategories_settingsoptions_userparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoptions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='drevo.parametercategories', verbose_name='Категория'),
        ),
    ]
