# Generated by Django 3.2.4 on 2023-01-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0039_auto_20230107_1031'),
        ('drevo', '0040_alter_settingsoptions_category'),
    ]

    operations = [
    ]
