# Generated by Django 3.2.4 on 2023-01-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0039_auto_20230108_1922'),
        ('drevo', '0041_merge_20230109_2237'),
    ]

    operations = [
    ]
