# Generated by Django 3.2.4 on 2023-01-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0042_merge_20230110_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tz',
            name='is_author_required',
            field=models.BooleanField(default=False, verbose_name='Автор обязателен для заполнения'),
        ),
        migrations.AddField(
            model_name='tz',
            name='is_href_required',
            field=models.BooleanField(default=False, verbose_name='Источник обязателен для заполнения'),
        ),
    ]
