# Generated by Django 3.2.4 on 2023-01-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0043_author_user_author'),
        ('drevo', '0043_auto_20230118_1641'),
    ]

    operations = [
    ]
