# Generated by Django 3.2.4 on 2023-02-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0044_merge_0043_author_user_author_0043_auto_20230118_1641'),
        ('drevo', '0044_message'),
    ]

    operations = [
    ]
