# Generated by Django 3.2.4 on 2023-02-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0044_merge_0043_author_user_author_0043_auto_20230118_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionsOfRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_knowledge_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='init_knowledge_types', to='drevo.tz')),
                ('related_knowledge_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_knowledge_types', to='drevo.tz')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_types', to='drevo.tr')),
            ],
            options={
                'verbose_name': 'Взаимосвязь видов',
                'verbose_name_plural': 'Взаимосвязи видов',
            },
        ),
    ]
