# Generated by Django 3.2.4 on 2023-02-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0045_interactionsofrelations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactionsofrelations',
            options={'ordering': ['pk'], 'verbose_name': 'Взаимосвязь видов', 'verbose_name_plural': 'Взаимосвязи видов'},
        ),
    ]
