# Generated by Django 3.2.4 on 2023-02-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0045_merge_20230201_1618'),
        ('drevo', '0045_merge_20230201_1629'),
    ]

    operations = [
    ]
