# Generated by Django 3.2.4 on 2023-02-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0046_merge_20230202_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgestatuses',
            options={'ordering': ['status'], 'verbose_name': 'Статус знания', 'verbose_name_plural': 'Статусы знания'},
        ),
    ]
