# Generated by Django 3.2.4 on 2023-02-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0047_alter_knowledgestatuses_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGradeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hue', models.IntegerField(verbose_name='Оттенок')),
                ('saturation', models.IntegerField(verbose_name='Насыщенность')),
                ('high_light', models.IntegerField(verbose_name='Верхняя яркость')),
                ('low_light', models.IntegerField(verbose_name='Нижняя яркость')),
                ('knowledge_type', models.BooleanField(choices=[(False, 'Любые знания'), (True, 'Довод "Против"')], default=False, verbose_name='Тип знания')),
            ],
            options={
                'verbose_name': 'Спектр цвета',
                'verbose_name_plural': 'Спектр цвета оценки знания',
            },
        ),
    ]
