# Generated by Django 4.1.1 on 2023-02-13 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0049_interviewanswerexpertproposal_incorrect_answer_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.BooleanField(default=False, verbose_name='Редактор')),
                ('admin_competencies', models.ManyToManyField(related_name='special_permissions', to='drevo.category', verbose_name='Компетенции руководителя')),
                ('categories', models.ManyToManyField(related_name='category_list', to='drevo.category', verbose_name='Компетенции эксперта')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Особые права',
                'verbose_name_plural': 'Особые права',
            },
        ),
        migrations.DeleteModel(
            name='CategoryExpert',
        ),
    ]
