# Generated by Django 4.1.1 on 2023-02-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0048_category_subscribers'),
        ('drevo', '0049_interviewanswerexpertproposal_incorrect_answer_explanation_and_more'),
    ]

    operations = [
    ]
