# Generated by Django 3.2.4 on 2023-02-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0048_knowledgegradecolor'),
        ('drevo', '0050_merge_20230215_1909'),
    ]

    operations = [
    ]
