# Generated by Django 4.1.1 on 2023-02-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0050_merge_20230215_1909'),
        ('drevo', '0050_specialpermissions_delete_'),
    ]

    operations = [
    ]
