# Generated by Django 3.2.4 on 2023-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0051_merge_20230216_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='znanie',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Уведомления'),
        ),
    ]
