# Generated by Django 4.1.1 on 2023-02-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0051_merge_20230216_2118'),
        ('drevo', '0052_alter_specialpermissions_expert'),
    ]

    operations = [
    ]
