# Generated by Django 3.2.4 on 2023-02-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0052_znanie_notification'),
        ('drevo', '0054_remove_interviewanswerexpertproposal_comment_and_more'),
    ]

    operations = [
    ]
