# Generated by Django 3.2.4 on 2023-03-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0055_merge_20230226_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgegradescale',
            options={'ordering': ('-order',), 'verbose_name': 'Градация', 'verbose_name_plural': 'Шкала оценок знаний'},
        ),
        migrations.AddField(
            model_name='knowledgegradescale',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
