# Generated by Django 4.1.1 on 2023-03-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0057_auto_20230311_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsoptions',
            name='is_bool',
            field=models.BooleanField(default=False, verbose_name='Логический'),
        ),
    ]
