# Generated by Django 4.1.1 on 2023-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0058_settingsoptions_is_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoptions',
            name='default_param',
            field=models.IntegerField(verbose_name='Значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='userparameters',
            name='param_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение параметра'),
        ),
    ]
