# Generated by Django 4.1.1 on 2023-03-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0059_alter_settingsoptions_default_param_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipTzTr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_tz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_tz_tr', to='drevo.tz', verbose_name='Вид базового знания')),
                ('rel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_tz_tr', to='drevo.tr', verbose_name='Вид связи')),
                ('rel_tz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_tz_tr', to='drevo.tz', verbose_name='Вид связанного знания')),
            ],
            options={
                'verbose_name': 'Взаимосвязи видов знаний и связей',
                'verbose_name_plural': 'Взаимосвязь вида знания и связи',
            },
        ),
    ]
