# Generated by Django 3.2.4 on 2023-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0062_alter_relationshiptztr_base_tz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='date',
            field=models.DateField(auto_now_add=True, default=(2023, 5, 11), verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
