# Generated by Django 4.1.1 on 2023-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0064_alter_relation_bz_alter_relation_rz_and_more'),
        ('drevo', '0065_alter_relation_bz'),
    ]

    operations = [
    ]
