# Generated by Django 4.1.1 on 2023-04-26 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0066_merge_20230425_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_director', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rel_expert', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='relationstatuses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_rel_status', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
