# Generated by Django 3.2.4 on 2023-05-17 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0067_alter_relation_director_alter_relation_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
