# Generated by Django 3.2.4 on 2023-05-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0063_visits_date'),
        ('drevo', '0067_alter_relation_director_alter_relation_expert_and_more'),
    ]

    operations = [
    ]
