# Generated by Django 3.2.4 on 2023-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0068_visits_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/developers/', verbose_name='Фото'),
        ),
    ]
