# Generated by Django 3.2.4 on 2023-06-22 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0069_developer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('question', 'Задать вопрос'), ('proposal', 'Сделать предложение по развитию сайта'), ('complaint', 'Заявить претензию'), ('profile_deletion', 'Удалить свой профиль')], max_length=200, verbose_name='Причина обращения')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('description', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Отвечено')),
                ('message', models.TextField(blank=True, max_length=1000, verbose_name='Ответ на обращение')),
                ('answered_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата ответа')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addressee', to=settings.AUTH_USER_MODEL, verbose_name='Ответивший на обращение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
            },
        ),
    ]
