# Generated by Django 3.2.4 on 2023-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0070_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='order',
            field=models.IntegerField(blank=True, help_text='укажите порядковый номер', null=True, verbose_name='Порядок'),
        ),
    ]
