# Generated by Django 3.2.4 on 2023-07-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0071_alter_appeal_subject'),
        ('drevo', '0071_relation_order'),
    ]

    operations = [
    ]
