# Generated by Django 3.2.4 on 2023-08-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0072_merge_0071_alter_appeal_subject_0071_relation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptztr',
            name='is_only_one_rel',
            field=models.BooleanField(default=False, verbose_name='Одна связь?'),
        ),
        migrations.AddField(
            model_name='tz',
            name='tr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.tr', verbose_name='Обязательный вид связи'),
        ),
    ]
