# Generated by Django 3.2.4 on 2023-09-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0073_algorithmdata_znfile'),
        ('drevo', '0073_auto_20230814_2134'),
    ]

    operations = [
    ]
