# Generated by Django 3.2.4 on 2023-09-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0073_auto_20230814_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionToKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drevo.znanie', verbose_name='Знание')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserAnswerToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Ответ')),
                ('answer_file', models.FileField(upload_to='', verbose_name='Файл')),
                ('accepted', models.BooleanField(default=False, verbose_name='Ответ принят')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Знание')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.questiontoknowledge', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы пользователя',
            },
        ),
    ]
