# Generated by Django 3.2.4 on 2023-09-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_suggestiontype_is_private'),
        ('drevo', '0074_merge_20230917_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='tz',
            name='available_suggestion_types',
            field=models.ManyToManyField(blank=True, to='users.SuggestionType', verbose_name='Типы предложений'),
        ),
    ]
