# Generated by Django 3.2.4 on 2023-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0076_auto_20230922_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontoknowledge',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
    ]
