# Generated by Django 3.2.4 on 2023-10-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0075_tz_available_suggestion_types'),
        ('drevo', '0077_questiontoknowledge_publication'),
    ]

    operations = [
    ]
