# Generated by Django 3.2.4 on 2023-10-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0078_merge_20231003_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tz',
            name='available_suggestion_types',
        ),
    ]
