# Generated by Django 3.2.4 on 2023-10-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0079_useranswertoquestion_inspector'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина отказа',
                'verbose_name_plural': 'Причины отказа',
            },
        ),
        migrations.AlterField(
            model_name='useranswertoquestion',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='proof/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='useranswertoquestion',
            name='refuse_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drevo.refusereason', verbose_name='Причина отказа'),
        ),
    ]
