# Generated by Django 3.2.4 on 2023-10-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0080_auto_20231016_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': ('Категорий терминов глоссария',),
                'verbose_name_plural': 'Категорий терминов глоссария',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drevo.glossarycategories', verbose_name='Категория'),
        ),
    ]
