# Generated by Django 3.2.4 on 2023-10-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0080_auto_20231016_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontoknowledge',
            name='need_file',
            field=models.BooleanField(default=False, verbose_name='Файл'),
        ),
    ]
