# Generated by Django 3.2.4 on 2023-10-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0080_suggestion_suggestiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tz',
            name='available_suggestion_types',
            field=models.ManyToManyField(blank=True, to='drevo.SuggestionType', verbose_name='Типы предложений'),
        ),
    ]
