# Generated by Django 3.2.4 on 2023-10-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0081_questiontoknowledge_need_file'),
        ('drevo', '0081_tz_available_suggestion_types'),
    ]

    operations = [
    ]
