# Generated by Django 3.2.4 on 2023-10-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0081_auto_20231018_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.glossarycategories', verbose_name='Категория'),
        ),
    ]
