# Generated by Django 3.2.4 on 2023-10-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0082_merge_20231025_1317'),
        ('drevo', '0082_questiontoknowledge_order'),
    ]

    operations = [
    ]
