# Generated by Django 3.2.4 on 2023-10-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0083_auto_20231026_2125'),
        ('drevo', '0083_merge_20231027_0314'),
    ]

    operations = [
    ]
