# Generated by Django 3.2.4 on 2023-10-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0084_alter_useranswertoquestion_answer_file'),
        ('drevo', '0084_merge_20231030_1518'),
    ]

    operations = [
    ]
