# Generated by Django 3.2.4 on 2023-11-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0085_merge_20231031_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmadditionalelements',
            name='algorithm',
            field=models.ForeignKey(limit_choices_to={'tz__name': 'Алгоритм'}, on_delete=django.db.models.deletion.CASCADE, related_name='changed_algorithm', to='drevo.znanie', verbose_name='Алгоритм'),
        ),
        migrations.AlterField(
            model_name='algorithmdata',
            name='algorithm',
            field=models.ForeignKey(limit_choices_to={'tz__name': 'Алгоритм'}, on_delete=django.db.models.deletion.CASCADE, related_name='passed_algorithm', to='drevo.znanie', verbose_name='Алгоритм'),
        ),
        migrations.AlterField(
            model_name='algorithmwork',
            name='algorithm',
            field=models.ForeignKey(limit_choices_to={'tz__name': 'Алгоритм'}, on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Алгоритм'),
        ),
    ]
