# Generated by Django 3.2.4 on 2023-10-31 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0085_merge_20231031_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr',
            name='has_invert',
            field=models.BooleanField(default=False, editable=False, verbose_name='Доступна инверсия'),
        ),
        migrations.AddField(
            model_name='tr',
            name='invert_tr',
            field=models.ForeignKey(blank=True, help_text='Только для инверсивных связей', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invert_rel_type', to='drevo.tr', verbose_name='Инверсия'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('bz', 'tr', 'rz'), name='bz_tr_rz_unique_constraint'),
        ),
    ]
