# Generated by Django 3.2.4 on 2023-11-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0084_auto_20231029_1649'),
        ('drevo', '0086_auto_20231101_0247'),
    ]

    operations = [
    ]
