# Generated by Django 3.2.4 on 2023-11-07 19:08

from django.db import migrations, models
import drevo.common.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0087_merge_0084_auto_20231029_1649_0086_auto_20231101_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossarycategories',
            options={'ordering': ('order',), 'verbose_name': 'Категорию терминов глоссария', 'verbose_name_plural': 'Категорий терминов глоссария'},
        ),
        migrations.AlterField(
            model_name='suggestiontype',
            name='weight',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='useranswertoquestion',
            name='answer_file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=drevo.common.file_storage.ASCIIFileSystemStorage(), upload_to='proof/', verbose_name='Файл'),
        ),
    ]
