# Generated by Django 3.2.4 on 2023-11-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0088_auto_20231102_1827'),
        ('drevo', '0088_auto_20231107_2208'),
    ]

    operations = [
    ]
