# Generated by Django 3.2.4 on 2023-11-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0090_auto_20231110_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionTypeClone',
            fields=[
                ('type_name', models.CharField(max_length=255, verbose_name='Название типа')),
                ('weight', models.IntegerField(blank=True, default=100, primary_key=True, serialize=False, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вид предложения',
                'verbose_name_plural': 'Виды предложений',
            },
        ),
    ]
