# Generated by Django 3.2.4 on 2023-11-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    def migrate_data(apps, schema_editor):
        SuggestionType = apps.get_model('drevo', 'SuggestionType')
        Clone = apps.get_model('drevo', 'SuggestionTypeClone')
        for i in SuggestionType.objects.all():
            Clone.objects.create(type_name=i.type_name, weight=i.weight)

    dependencies = [
        ('drevo', '0091_suggestiontypeclone'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
