# Generated by Django 3.2.4 on 2023-12-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0086_auto_20231124_1412'),
        ('drevo', '0091_auto_20231120_0719'),
    ]

    operations = [
    ]
