# Generated by Django 3.2.4 on 2023-12-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0091_auto_20231120_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название главы')),
                ('content', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(blank=True, help_text='Укажите порядковый номер', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Глава описания',
                'verbose_name_plural': 'Главы описания',
                'ordering': ('order',),
            },
        ),
    ]
