# Generated by Django 3.2.4 on 2023-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0093_auto_20231111_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiontype',
            name='weight2',
            field=models.IntegerField(blank=True, default=100, verbose_name='Порядок'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='suggestiontype',
            old_name='weight',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='suggestiontype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='suggestiontype',
            old_name='weight2',
            new_name='weight'
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestions_type',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='drevo.suggestiontype', verbose_name='Вид предложения'),
        ),
        migrations.AlterField(
            model_name='tz',
            name='available_suggestion_types',
            field=models.ManyToManyField(blank=True, to='drevo.SuggestionType', verbose_name='Виды предложений'),
        ),
    ]
