# Generated by Django 3.2.4 on 2024-01-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0092_merge_0086_auto_20231124_1412_0091_auto_20231120_0719'),
        ('drevo', '0093_chapterdescriptions'),
    ]

    operations = [
    ]
