# Generated by Django 3.2.4 on 2023-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0093_auto_20231111_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiontype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestiontype',
            name='weight',
            field=models.IntegerField(blank=True, default=100, verbose_name='Порядок'),
        ),
    ]
