# Generated by Django 3.2.4 on 2023-11-11 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('drevo', '0094_auto_20231111_2025'),
    ]

    operations = []
