# Generated by Django 3.2.4 on 2023-11-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0095_auto_20231111_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestions_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.suggestiontype', verbose_name='Вид предложения'),
        ),
        migrations.AlterField(
            model_name='tz',
            name='available_suggestion_types',
            field=models.ManyToManyField(blank=True, to='drevo.SuggestionType', verbose_name='Виды предложений'),
        ),
    ]
