# Generated by Django 3.2.4 on 2023-11-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0096_auto_20231111_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestionTypeClone',
        ),
    ]