# Generated by Django 3.2.4 on 2023-11-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0098_auto_20231119_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='connected_to',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='drevo.var', verbose_name='Подчинение'),
        ),
        migrations.AddField(
            model_name='var',
            name='is_array',
            field=models.BooleanField(default=False, verbose_name='Массив'),
        ),
        migrations.AddField(
            model_name='var',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Глобальная'),
        ),
        migrations.AddField(
            model_name='var',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
        migrations.AddField(
            model_name='var',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
