# Generated by Django 3.2.4 on 2023-12-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0099_auto_20231128_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='fill_title',
            field=models.TextField(blank=True, default='', verbose_name='Обращение'),
        ),
    ]
