# Generated by Django 3.2.4 on 2023-12-05 07:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0100_var_fill_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_global', models.BooleanField(default=False, verbose_name='Глобальный')),
                ('weight', models.IntegerField(default=100, verbose_name='Порядок')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Знание')),
            ],
        ),
        migrations.AddField(
            model_name='var',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Прописью'),
        ),
        migrations.AddField(
            model_name='var',
            name='type_of',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2, 'Неопознанный тип переменной'), django.core.validators.MinValueValidator(0, 'Неопознанный тип переменной')], verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='TurpleElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Содержание')),
                ('weight', models.IntegerField(default=100, verbose_name='Порядок')),
                ('turple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.turple', verbose_name='Справочник')),
            ],
        ),
        migrations.AddField(
            model_name='var',
            name='turple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.turple', verbose_name='Справочник'),
        ),
    ]
