# Generated by Django 3.2.4 on 2023-12-10 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0101_auto_20231205_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turple',
            options={'verbose_name': 'Словарь', 'verbose_name_plural': 'Словари'},
        ),
        migrations.AlterModelOptions(
            name='turpleelement',
            options={'verbose_name': 'Элемент словаря', 'verbose_name_plural': 'Элементы словаря'},
        ),
        migrations.AlterModelOptions(
            name='var',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты документа'},
        ),
        migrations.RemoveField(
            model_name='var',
            name='is_array',
        ),
        migrations.AddField(
            model_name='var',
            name='structure',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Неопознанный тип объекта'), django.core.validators.MaxValueValidator(3, 'Неопознанный тип объекта')], verbose_name='Массив'),
        ),
        migrations.AlterField(
            model_name='var',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя объекта'),
        ),
        migrations.AlterField(
            model_name='var',
            name='type_of',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2, 'Неопознанный тип содержимого объекта'), django.core.validators.MinValueValidator(0, 'Неопознанный тип содержимого объекта')], verbose_name='Тип'),
        ),
    ]
