# Generated by Django 3.2.4 on 2023-12-12 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0102_auto_20231210_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='var',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты шаблонов'},
        ),
        migrations.AlterField(
            model_name='var',
            name='structure',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Неопознанный тип объекта'), django.core.validators.MaxValueValidator(3, 'Неопознанный тип объекта')], verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='var',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Порядок'),
        ),
    ]
