# Generated by Django 3.2.4 on 2023-12-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0103_auto_20231212_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='optional',
            field=models.BooleanField(default=False, verbose_name='Необязательность'),
        ),
    ]
