# Generated by Django 3.2.4 on 2023-12-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0104_var_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='turpleelement',
            name='var',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.var', verbose_name='Переменная'),
        ),
    ]
