# Generated by Django 3.2.4 on 2023-12-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0105_turpleelement_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='structure',
            field=models.IntegerField(choices=[(2, 'Управление'), (3, 'Справочник'), (0, 'Переменная'), (1, 'Массив')], default=0, verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='var',
            name='type_of',
            field=models.IntegerField(choices=[(0, 'Текст'), (1, 'Число'), (2, 'Дата')], default=0, verbose_name='Тип'),
        ),
    ]
