# Generated by Django 3.2.4 on 2024-01-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0094_merge_20240105_2105'),
        ('drevo', '0107_auto_20240104_2027'),
    ]

    operations = [
    ]
