# Generated by Django 3.2.4 on 2024-01-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0109_suggestionkind'),
    ]

    operations = []
