# Generated by Django 3.2.4 on 2024-01-11 17:46

from django.db import migrations

def foo(apps, schema_editor):
    """
        Перенос данных из SuggestionType в SuggestionKind
    """
    Kind = apps.get_model('drevo', 'SuggestionKind')
    Type = apps.get_model('drevo', 'SuggestionType')

    for i in Type.objects.all():
        Kind.create(weight=i.weight, type_name=i.type_name)


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0109_suggestionkind'),
    ]

    operations = [
        migrations.RunPython(foo),
    ]
