# Generated by Django 3.2.4 on 2024-01-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0110_auto_20240111_2046'),
    ]

    operations = []
