# Generated by Django 3.2.4 on 2024-01-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0111_auto_20240111_2107'),
    ]

    operations = [
    ]