# Generated by Django 3.2.4 on 2024-01-26 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0113_auto_20240124_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название документа')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('word', models.FileField(blank=True, null=True, upload_to='word/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
