# Generated by Django 3.2.4 on 2024-01-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0115_auto_20240128_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Родительский документ'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='word',
            field=models.FileField(blank=True, null=True, upload_to='word/', verbose_name='WORD'),
        ),
    ]
