# Generated by Django 3.2.4 on 2024-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0116_auto_20240131_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='structure',
            field=models.IntegerField(choices=[(0, 'Переменная'), (1, 'Массив'), (3, 'Итератор'), (4, 'Условие')], default=0, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='var',
            name='type_of',
            field=models.IntegerField(choices=[(0, 'Текст'), (1, 'Число'), (2, 'Дата'), (3, 'Справочник')], default=0, verbose_name='Вид значения'),
        ),
    ]
