# Generated by Django 3.2.4 on 2024-01-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0116_auto_20240128_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdocuments',
            old_name='category',
            new_name='root_document',
        ),
    ]
