# Generated by Django 3.2.4 on 2024-02-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0118_alter_var_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turple',
            options={'ordering': ('weight',), 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='turpleelement',
            options={'ordering': ('weight',), 'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочника'},
        ),
    ]
