# Generated by Django 3.2.4 on 2024-02-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0117_rename_category_usersdocuments_root_document'),
        ('drevo', '0119_auto_20240205_2029'),
    ]

    operations = [
    ]
