# Generated by Django 3.2.4 on 2024-02-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0119_auto_20240205_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turple',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='turple',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='turpleelement',
            name='var',
        ),
        migrations.AlterField(
            model_name='var',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Знание'),
        ),
    ]
