# Generated by Django 3.2.4 on 2024-02-08 10:55

from django.db import migrations


def change_structure_val(apps, schema_editor):
    Var = apps.get_model('drevo', 'Var')
    for i in Var.objects.all():
        if i.structure == 3:
            i.structure = 2
            i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0120_auto_20240208_1351'),
    ]

    operations = [
        migrations.RunPython(change_structure_val),
    ]
