# Generated by Django 3.2.4 on 2024-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0120_merge_20240210_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='is_complete',
            field=models.BooleanField(blank=True, null=True, verbose_name='Завершено'),
        ),
    ]
