# Generated by Django 3.2.4 on 2024-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0121_usersdocuments_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
