# Generated by Django 3.2.4 on 2024-02-11 14:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0122_auto_20240208_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя объекта')),
                ('structure', models.IntegerField(choices=[(0, 'Переменная'), (1, 'Массив'), (2, 'Управление')], default=0, verbose_name='Тип объекта')),
                ('is_main', models.BooleanField(default=False, verbose_name='Группа')),
                ('availability', models.IntegerField(choices=[(0, 'Локальный'), (1, 'Глобальный'), (2, 'Общий')], default=0, verbose_name='Класс объекта')),
                ('weight', models.IntegerField(default=1, verbose_name='Порядок')),
                ('fill_title', models.TextField(blank=True, default='', verbose_name='Обращение')),
                ('subscription', models.BooleanField(default=False, verbose_name='Прописью')),
                ('optional', models.BooleanField(default=False, verbose_name='Необязательность')),
                ('type_of', models.IntegerField(choices=[(0, 'Текст'), (1, 'Число'), (2, 'Дата'), (3, 'Справочник')], default=0, verbose_name='Вид значения')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('connected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drevo.templateobject', verbose_name='Родитель')),
                ('knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Знание')),
                ('mptt_parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mptt_children', to='drevo.templateobject')),
                ('turple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.turple', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты шаблонов',
                'ordering': ('weight',),
            },
        ),
    ]
