# Generated by Django 3.2.4 on 2024-02-25 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0122_alter_usersdocuments_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersdocuments',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
