# Generated by Django 3.2.4 on 2024-03-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0122_alter_usersdocuments_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название статуса')),
                ('text_for_users', models.CharField(max_length=128, verbose_name='Текст для пользователя')),
            ],
            options={
                'verbose_name': 'Вид статуса страниц',
                'verbose_name_plural': 'Виды статусов страниц',
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('group', 'Группа'), ('page', 'Страница'), ('type_of_complicated_knowledge', 'Вид сложного знания'), ('complicated_knowledge', 'Сложное знание'), ('label', 'Ярлык')], max_length=255, verbose_name='Тип')),
                ('functional', models.BooleanField(default=False, verbose_name='Функционал')),
                ('design_needed', models.BooleanField(default=False, verbose_name='Необходимость макета')),
                ('design', models.BooleanField(default=False, verbose_name='Макет')),
                ('layout', models.BooleanField(default=False, verbose_name='Верстка')),
                ('help_page', models.BooleanField(default=False, verbose_name='Страница помощи')),
                ('help_page_content', models.BooleanField(default=False, verbose_name='Контент помощи')),
                ('notification', models.BooleanField(default=False, verbose_name='Оповещение')),
                ('link', models.URLField(blank=True, max_length=256, null=True, verbose_name='URL-адрес')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('base_page', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='drevo.sitepage', verbose_name='Базовая страница')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Страница')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drevo.sitepage', verbose_name='Родитель')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drevo.statustype', verbose_name='Статус')),
                ('subscribers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписчики')),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
            },
        ),
        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(choices=[('parent', 'Родитель'), ('type', 'Тип'), ('base_page', 'Базовая страница'), ('functional', 'Функционал'), ('design_needed', 'Необходимость макета'), ('design', 'Макет'), ('layout', 'Верстка'), ('help_page', 'Страница помощи'), ('help_page_content', 'Контент помощи'), ('notification', 'Оповещение'), ('status', 'Статус'), ('link', 'URL-адрес'), ('subscribers', 'Подписчики')], max_length=255, verbose_name='Реквизиты')),
                ('previous_value', models.CharField(max_length=256, verbose_name='Предыдущее значение')),
                ('last_value', models.CharField(max_length=256, verbose_name='Последнее значение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.sitepage', verbose_name='Страница')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'История изменения страницы',
                'verbose_name_plural': 'История изменений страниц',
            },
        ),
    ]
