# Generated by Django 3.2.4 on 2024-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0123_auto_20240225_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее изменение'),
        ),
    ]
