# Generated by Django 3.2.4 on 2024-02-11 08:59

from django.db import migrations
from django.db import transaction

@transaction.atomic
def create_newvar_instance(new_var, var_instance, new_var_parent=None):
    instance = new_var.objects.create(
        name=var_instance.name,
        structure=var_instance.structure,
        is_main=var_instance.is_main,
        availability=var_instance.availability,
        weight=var_instance.weight,
        fill_title=var_instance.fill_title,
        subscription=var_instance.subscription,
        optional=var_instance.optional,
        type_of=var_instance.type_of,
        knowledge=var_instance.knowledge,
        connected_to=new_var_parent,
        turple=var_instance.turple,
        comment=var_instance.comment,
        mptt_parent=new_var_parent,
        lft=0,
        rght=0,
        level=0,
        tree_id=0,
        )

    return instance


def data_translate(apps, schema_editor):
    stack = []
    Var = apps.get_model('drevo', 'Var')
    NewVar = apps.get_model('drevo', 'TemplateObject')

    for i in Var.objects.all():
        if i.connected_to is None:
            stack.append((i, create_newvar_instance(NewVar, i)))

    while len(stack):
        v = stack.pop()
        for i in v[0].var_set.all():
            stack.append((i, create_newvar_instance(NewVar, i, v[1])))


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0123_templateobject'),
    ]

    operations = [
        migrations.RunPython(data_translate)
    ]
