# Generated by Django 3.2.4 on 2024-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0124_alter_usersdocuments_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdocuments',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Содержание'),
        ),
    ]
