# Generated by Django 3.2.4 on 2024-03-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0125_alter_usersdocuments_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='meta_info',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Метаинформация'),
        ),
        migrations.AddField(
            model_name='znanie',
            name='meta_info',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Метаинформация'),
        ),
    ]
