# Generated by Django 3.2.4 on 2024-03-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0125_remove_templateobject_mptt_parent'),
        ('drevo', '0126_auto_20240306_1603'),
    ]

    operations = [
    ]
