# Generated by Django 3.2.4 on 2024-03-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0123_pagehistory_sitepage_statustype'),
        ('drevo', '0127_merge_20240312_2301'),
    ]

    operations = [
    ]
