# Generated by Django 3.2.4 on 2024-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0128_auto_20240326_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateobject',
            name='templates_that_use',
            field=models.ManyToManyField(related_name='template_objects_set', to='drevo.Znanie', verbose_name='Включающие шаблоны'),
        ),
    ]
