# Generated by Django 3.2.4 on 2024-03-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0128_merge_20240330_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehistory',
            name='last_value',
            field=models.CharField(max_length=256, null=True, verbose_name='Последнее значение'),
        ),
        migrations.AlterField(
            model_name='pagehistory',
            name='previous_value',
            field=models.CharField(max_length=256, null=True, verbose_name='Предыдущее значение'),
        ),
    ]
