# Generated by Django 3.2.4 on 2024-04-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0129_auto_20240331_1112'),
        ('drevo', '0130_alter_templateobject_templates_that_use'),
    ]

    operations = [
    ]
