# Generated by Django 3.2.4 on 2024-05-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0131_merge_20240406_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='pagehistory',
            name='prop',
            field=models.CharField(choices=[('parent', 'Родитель'), ('type', 'Тип'), ('base_page', 'Базовая страница'), ('functional', 'Функционал'), ('design_needed', 'Необходимость макета'), ('design', 'Макет'), ('layout', 'Верстка'), ('help_page', 'Страница помощи'), ('help_page_content', 'Контент помощи'), ('notification', 'Оповещение'), ('status', 'Статус'), ('link', 'URL-адрес'), ('subscribers', 'Подписчики'), ('order', 'Порядок')], max_length=255, verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drevo.statustype', verbose_name='Статус'),
        ),
    ]
