# Generated by Django 3.2.4 on 2024-07-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0131_merge_20240406_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='turpleelement',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuple_elements', to='drevo.turple', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='templateobject',
            name='type_of',
            field=models.IntegerField(choices=[(0, 'Текст'), (1, 'Число'), (2, 'Дата'), (3, 'Справочник'), (3, 'Составной')], default=0, verbose_name='Вид значения'),
        ),
    ]
