# Generated by Django 3.2.4 on 2024-07-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0132_auto_20240526_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drevo.znanie', verbose_name='Страница'),
        ),
    ]
