# Generated by Django 3.2.4 on 2024-07-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0132_auto_20240526_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admin_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_records', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drevo.tablename')),
            ],
        ),
    ]
