# Generated by Django 3.2.4 on 2024-07-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0132_auto_20240723_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateobject',
            name='type_of',
            field=models.IntegerField(choices=[(0, 'Текст'), (1, 'Число'), (2, 'Дата'), (3, 'Справочник'), (4, 'Составной')], default=0, verbose_name='Вид значения'),
        ),
        migrations.AlterField(
            model_name='turpleelement',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuple_elements', to='drevo.templateobject', verbose_name='Объект'),
        ),
    ]
