# Generated by Django 3.2.4 on 2024-07-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0133_auto_20240725_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turpleelement',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuple_elements', to='drevo.templateobject', verbose_name='Объект'),
        ),
    ]
