# Generated by Django 3.2.4 on 2024-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0133_tablename_tablestate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablestate',
            options={'verbose_name': 'Состояние таблицы', 'verbose_name_plural': 'Состояния таблиц'},
        ),
        migrations.AlterField(
            model_name='tablestate',
            name='table_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TableName',
        ),
    ]
