# Generated by Django 3.2.4 on 2024-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0134_auto_20240712_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestate',
            name='difference',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
