# Generated by Django 3.2.4 on 2024-07-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0133_alter_sitepage_page'),
        ('drevo', '0134_alter_turpleelement_object'),
    ]

    operations = [
    ]
