# Generated by Django 3.2.4 on 2024-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0135_tablestate_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestate',
            name='difference',
            field=models.IntegerField(blank=True),
        ),
    ]
