# Generated by Django 3.2.4 on 2024-08-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0136_alter_tablestate_difference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgegradescale',
            options={'ordering': ('order',), 'verbose_name': 'Шкала оценки знаний', 'verbose_name_plural': 'Шкала оценок знаний'},
        ),
    ]
