# Generated by Django 3.2.4 on 2024-08-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0135_merge_20240725_2250'),
        ('drevo', '0137_alter_knowledgegradescale_options'),
    ]

    operations = [
    ]
