# Generated by Django 3.2.4 on 2024-08-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0138_merge_20240807_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsoptions',
            name='id',
            field=models.IntegerField(choices=[(1, 'Param 1'), (2, 'Param 2'), (3, 'Param 3'), (4, 'Param 4'), (5, 'Rec For Page'), (6, 'Content Words'), (7, 'Min Time'), (8, 'Min Expert'), (9, 'Min Director'), (10, 'Min Knowledge For Expert'), (11, 'Expert Period'), (12, 'Score Variant'), (13, 'Not Use Again'), (14, 'Use Structure Knowledge'), (15, 'Search In Content'), (16, 'Search In Comment'), (17, 'Not Provided Knowledge'), (18, 'Most Popular Count'), (19, 'Param 19'), (20, 'Param 20')], primary_key=True, serialize=False),
        ),
    ]
