# Generated by Django 3.2.4 on 2024-08-10 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drevo', '0139_alter_settingsoptions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
