# Generated by Django 3.2.4 on 2024-08-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0136_alter_settingsoptions_id'),
        ('drevo', '0139_alter_settingsoptions_id'),
    ]

    operations = [
    ]
