# Generated by Django 3.2.4 on 2024-09-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0140_merge_20240816_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateobject',
            name='template',
            field=models.TextField(blank=True, null=True, verbose_name='Шаблон объекта'),
        ),
    ]
