# Generated by Django 3.2.4 on 2024-09-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0141_commentrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentRating',
        ),
    ]
