# Generated by Django 3.2.4 on 2024-09-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0141_templateobject_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateobject',
            name='template',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Шаблон'),
        ),
    ]
