# Generated by Django 3.2.4 on 2024-10-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drevo', '0142_alter_templateobject_template'),
        ('drevo', '0142_delete_commentrating'),
    ]

    operations = [
    ]
