- name: install sources
  ansible.builtin.git:
    repo: 'https://github.com/lvb555/derzn.git'
    dest: '{{ project_root }}'
    version: '{{ git_ref_to_install }}'
    force: yes

- name: copy env_config
  ansible.builtin.copy:
    src: '{{ envs_file }}'
    dest: '{{ project_root }}/dz/.env'
  tags: ["envs", "configure"]

- name: copy settings file
  ansible.builtin.copy:
    src: '{{ settings_file }}'
    dest: '{{ project_root }}/dz/settings.py'
  tags: ["settings", "configure"]

- name: copy passenger file
  ansible.builtin.copy:
    src: '{{ passenger_file }}'
    dest: '{{ site_root }}/passenger_wsgi.py'
  tags: ['configure', 'passenger']

- name: upgrade pip
  ansible.builtin.pip:
    name: pip
    virtualenv: '{{ virtualenv_dir }}'
    extra_args: '--upgrade'
  tags: ["deps"]

- name: create virtualenv & install dependencies
  ansible.builtin.pip:
    virtualenv: '{{ virtualenv_dir }}'
    requirements: '{{ project_root }}/requirements.txt'
  tags: ["venv", "deps"]

- name: migrate
  community.general.django_manage:
    virtualenv: '{{ virtualenv_dir }}'
    project_path: '{{ project_root }}'
    # pythonpath: '{{ virtualenv_dir }}/lib/python3.10/site_packages'
    command: migrate
  tags: ["migrate"]

- name: restart
  ansible.builtin.file:
    state: touch
    path: '{{ site_root }}/.restart-app'
  # run this with any tag
  tags: ["restart", "migrate", "configure", "envs", "deps", "venv", "settings", "passenger"]
